---
abstract: 'OO interface for testing low-level Plack/PSGI apps'
author:
  - 'chromatic <chromatic@wgz.org>'
build_requires:
  HTTP::Cookies: 0
  Modern::Perl: 0
  Module::Build: 0.3601
  Plack::Request: 0
  Test::More: 0
  open: 0
  utf8: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Test-Agent
requires:
  HTTP::Message::PSGI: 0
  HTTP::Request::Common: 0
  HTTP::Response: 0
  Plack::Loader: 0
  Plack::Util::Accessor: 0
  Test::TCP: 0
  Test::WWW::Mechanize: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/chromatic/Plack-Test-Agent
  repository: https://github.com/chromatic/Plack-Test-Agent.git
version: 1.20111011
